### ISSUE TITLE
An updater for the WinBox emulator.

### ISSUE THREAD

**Issue by explorerdotexe** [laciba96/WinBox-for-86Box#15]
**Describe the feature you want to request**
A simple but effective WinBox updater, similar to the one used for 86Box updates.

**Give some reasons why it would be good for anyone else**
This feature is useful if you want to update WinBox, but don't want to constantly revisit the GitHub page.

**Describe the solution you'd like**
An updater that fetches the latest release from this github page, from downloading an .exe to a chosen path or something more complex.

**Comment by laciba96** [comment]
It's a good idea, I'll see what can I do. 

Probably it won't be such advanced as the emulator update, but I came up with an initial concept. 

Since I can't check that the user has the portable version, or the installer one, the program will search for updates, and then will offer a direct link to the downloads (if it's possible).

Replacing the files internally is complicated since if the program is in the Program Files directory, it needs admin rights to replace files, and also WinBox can't replace it's main executable while it's running.

My idea is comparing the version numbers, then offering direct downlaod link to the new release's installer like many open source program does. By closing WinBox itself and starting the installer, the process can be semi-automatic like at Notepad++. 

I'll check what API can GitHub offer to accomplish this. This feature probably takes some time to implement.

**Comment by laciba96** [comment]
The feature you've requested is added to v1.0.0.714. 
If everything works perfectly this could be the last version you need to download from GitHub, if you've used the installer version before. The users of portable version had to update manually, but they will also get a notificiation about the updates (if they want).

In the Program Settings I've added 4 options, according to the program update.
  - **Do not search for new WinBox versions**
     No auto-update, the action in Tools menu just opens the latest release page if there is update.
  - **Manual download option, custom update** 
    Checks for updates on startup, and if you click Yes the latest release page will open in your browser.
    This is the recommended solution for **portable version users**.
  - **Installer download, guided installation**
    Checks for updates on startup, and if you click Yes downloads and starts the Installer. 
    The program will close and can be restarted (optional) during the process.
    You can control the process by clicking through Next manually. 
    Can be used for **debugging** if the default option won't work.
  - **Installer download, automatic installation** (default)
    Checks for updates on startup, and if you click Yes downloads and starts the Installer.
    The process is fully automatic, the user will see that WinBox closes, the setup asks for admin rights (if installed to Program Files before), and the WinBox restarts with the new version. No progress, just fast installation and restart.
    This is the best options for the **installer version users**.
    
Since this is the first version with the updater, I couldn't do all the test I've wanted, so I just hope that my double-checks in my code should does the stuff. If there are problems with the new feature, it can be fixed in future releases.
