### ISSUE TITLE
"error reading zip file" while installing/updating emulator via WinBox For 86Box

### ISSUE THREAD

**Issue by TheNoob1703** [laciba96/WinBox-for-86Box#33]
<ERROR_DESCRIPTION>

There is an issue while I try to install/update the 86Box emulator files, like it's downloading properly, but then, this error message appears and aborts any installation

The program downloaded correctly the packages from the repo, and attempts to decompress the .zip file and this message appears:

There was an unhandled exception during the execution
Error opening the zip file.

below the description, I'm attaching the .log file for more information about the issue and my computer specs

Intel I7-7700K
8GB DDR-4 ram single channel
2TB Seagate Barracuda Compute 7200 Rpm
Windows 11 Pro x64

<AWAITING_REPLY>

<.LOG_ATTACHED_OK>
[WinBox.exe-exception-2021-11-19_19-05-42.log](https://github.com/laciba96/WinBox-for-86Box/files/7572188/WinBox.exe-exception-2021-11-19_19-05-42.log)

**Comment by laciba96** [comment]
Thank you for the report. 

This issue is related to the latest Jenkins changes on ci.86box.net. Currently I'm finding the fix for that problem, but it may take a while. As my plans the next WinBox version will fix that problem, but I'd ask for same patience about that.

While this version being developed, I'd recommend manual updating, and disabling automatic updates to avoid problems with the feature. I will inform you here when there is some progress.

**Comment by TheNoob1703** [comment]
Thank you

**Comment by laciba96** [comment]
The new version is out, which should solve this problem. Issue closed.
