### ISSUE TITLE
WinBox doesn't keep manual window resize setting.

### ISSUE THREAD

**Issue by DimMan88** [laciba96/WinBox-for-86Box#40]
An other "issue" I noticed is that Winbox doesn't keep the manual window resize, sidebar width etc.

On every start, window resets back to default size.

**Comment by laciba96** [comment]
If you are meaning the saving of the list width, and the manager's window size, you're right - this is currently unimplemented. 

<img width="651" alt="2021-12-04_23h26_01" src="https://user-images.githubusercontent.com/84271678/144726390-8f85552a-a528-47f7-900c-42c757c286fc.png">

Adjusting the manager window like this, and restarting the program resets all the adjustments currently.
If you want to ask for changing this behavior, probably it's more like a feature request.

Please tell me that did I interpreted your question well, or not - since if I did, I can mark this issue as feature request, rather than a bug.

**Comment by DimMan88** [comment]
Yes, change it to Feature Request.
I would be nice in a future release the feat. to remember size / position.

**Comment by laciba96** [comment]
I have some good news about your feature request. 
You can read these in my latest announcement https://github.com/laciba96/WinBox-for-86Box/discussions/46.

**Comment by DimMan88** [comment]
GREAT !

**Comment by laciba96** [comment]
The requested feature is added with the Grand Rewrite v2, so I close this issue.
